190 correct lazy delegate test case name and documentation
CoinFabrik/scout pull request #191
Opened 2023-08-30 19:50 UTC by arturoBeccar

#190

2023-08-31 14:13 UTC, aon approved these changes

2023-08-31 14:18 UTC, faculerena requested changes

2023-08-31 14:18 UTC, faculerena commented on docs/docs/vulnerabilities/23-lazy-delegate.md
> +- Vulnerability Category: `Authorization`
This is not an "Authorization" vulnerability. This is an implementation error as seen in [#1826 of ink!](https://github.com/paritytech/ink/issues/1826).

2023-08-31 14:18 UTC, faculerena commented on docs/docs/vulnerabilities/README.md
> +and has a Critical severity.
Idem

2023-09-04 14:14 UTC, arturoBeccar commented on docs/docs/vulnerabilities/23-lazy-delegate.md
> +- Vulnerability Category: `Authorization`
Added and updated category to Known Bugs

2023-09-04 15:10 UTC, faculerena approved these changes

2023-09-04 18:32 UTC, merged